FROM tomcat

RUN useradd tomcat

COPY lovecunit.war /usr/local/tomcat/webapps

ENTRYPOINT catalina.sh
CMD run

















#FROM tomcat
#RUN useradd tomcat
#COPY lovecunit.war /usr/local/tomcat/webapps/
#ENTRYPOINT catalina.sh
#CMD run
