apiVersion: v1
kind: Pod
metadata:
  name: imgvol 
spec:
  containers:
    - name: echoserver 
      image: registry.k8s.io/e2e-test-images/echoserver:2.3
      volumeMounts:
        - name: volume
          mountPath: /volume
  volumes:
    - name: volume
      image:
        reference: cgr.dev/chainguard/busybox:latest
        pullPolicy: IfNotPresent
